
export default {
    APP_LOADING:          'APP_LOADING',
    CHANGE_TASK_MESSAGE:  'CHANGE_TASK_MESSAGE',
    CLEAR_TASK_EDIT:      'CLEAR_TASK_EDIT',
    CREATE_TASK:          'CREATE_TASK',
    CREATE_TASK_SUCCESS:  'CREATE_TASK_SUCCESS',
    DELETE_TASK:          'DELETE_TASK',
    DELETE_TASK_SUCCESS:  'DELETE_TASK_SUCCESS',
    FETCH_TASKS:          'FETCH_TASKS',
    FETCH_TASKS_SUCCESS:  'FETCH_TASKS_SUCCESS',
    SEARCH_TASKS:         'SEARCH_TASKS',
    TASK_INPUT_CHANGE:    'TASK_INPUT_CHANGE',
    TOGGLE_TASK_EDIT:     'TOGGLE_TASK_EDIT',
    UPDATE_TASKS:         'UPDATE_TASKS',
    UPDATE_TASKS_SUCCESS: 'UPDATE_TASKS_SUCCESS',
};
