
export default {
    APP_LOADING:         'APP_LOADING',
    CREATE_TASK:         'CREATE_TASK',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    DELETE_TASK:         'DELETE_TASK',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    FETCH_TASKS:         'FETCH_TASKS',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
    TASK_INPUT_CHANGE:   'TASK_INPUT_CHANGE',
};
