
export default {
    APP_LOADING:         'APP_LOADING',
    CHANGE_TASK_MESSAGE: 'CHANGE_TASK_MESSAGE',
    CLEAR_TASK_EDIT:     'CLEAR_TASK_EDIT',
    CREATE_TASK:         'CREATE_TASK',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    DELETE_TASK:         'DELETE_TASK',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    FETCH_TASKS:         'FETCH_TASKS',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
    TASK_INPUT_CHANGE:   'TASK_INPUT_CHANGE',
    TOGGLE_TASK_EDIT:    'TOGGLE_TASK_EDIT',
    UPDATE_TASK:         'UPDATE_TASK',
    UPDATE_TASK_SUCCESS:         'UPDATE_TASK_SUCCESS',
};
